# Generated by Django 5.0 on 2023-12-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagereport',
            old_name='size',
            new_name='total_size',
        ),
        migrations.RenameField(
            model_name='videoreport',
            old_name='size',
            new_name='total_size',
        ),
    ]
