# Generated by Django 5.0 on 2024-01-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_size_imagereport_total_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldatareport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaldatareport',
            name='website',
        ),
        migrations.RemoveField(
            model_name='hostingprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='page',
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagereport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagereport',
            name='website',
        ),
        migrations.RemoveField(
            model_name='videoreport',
            name='page',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='page',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='websitereport',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarbonFootprintReport',
        ),
        migrations.DeleteModel(
            name='HistoricalDataReport',
        ),
        migrations.DeleteModel(
            name='HostingProvider',
        ),
        migrations.DeleteModel(
            name='ImageReport',
        ),
        migrations.DeleteModel(
            name='PageReport',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='VideoReport',
        ),
        migrations.DeleteModel(
            name='WebsiteReport',
        ),
    ]
