# Generated by Django 5.0 on 2024-01-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitereport',
            name='url',
            field=models.URLField(),
        ),
    ]
