# Generated by Django 5.0 on 2024-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_websitereport_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_score',
            field=models.FloatField(default=0.0),
        ),
    ]
