# Generated by Django 5.0 on 2024-01-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_carbonfootprintreport_carbon_footprint_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_images',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_other',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_videos',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='total_energy_usage',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='total_size',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pagereport',
            name='page_size',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='total_size',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(
            name='HistoricalDataReport',
        ),
    ]
