# Generated by Django 5.0 on 2024-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_carbonfootprintreport_carbon_footprint_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_images',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_other',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='carbon_footprint_videos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carbonfootprintreport',
            name='total_energy_usage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='total_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagereport',
            name='page_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='total_size',
            field=models.FloatField(),
        ),
    ]
