# Generated by Django 5.0 on 2024-01-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_carbonfootprintreport_carbon_footprint_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingprovider',
            name='user',
        ),
    ]
