# Generated by Django 5.0 on 2024-01-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_hostingprovider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingprovider',
            name='url',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
